/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

import br.com.ifrn.panfleto.utilitario.abrirPasta;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author herlan
 */
public class GerarPangletoEvento extends javax.swing.JFrame {

    /**
     * Creates new form GerarPangletoEvento
     */
    public GerarPangletoEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        painelCadastrar = new javax.swing.JPanel();
        labelCadastrarEvento = new javax.swing.JLabel();
        comboxCadastrarEvento = new javax.swing.JComboBox();
        btnCadastrarEventoOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        btnGerarPdfOk = new javax.swing.JButton();
        painelEsporte = new javax.swing.JPanel();
        labelTituloCadastrarEsporte = new javax.swing.JLabel();
        cadastrarEquipeEsporteScroll = new javax.swing.JScrollPane();
        cadastrarEquipeEsporte = new javax.swing.JTextArea();
        labelEquipeEsporte = new javax.swing.JLabel();
        labelNomeEsporte = new javax.swing.JLabel();
        txtNomeEsporte = new javax.swing.JTextField();
        painelFilme = new javax.swing.JPanel();
        labelCadastrarFilme = new javax.swing.JLabel();
        labelNomeFilme = new javax.swing.JLabel();
        txtNomeFilme = new javax.swing.JTextField();
        labelGeneroFilme = new javax.swing.JLabel();
        txtGeneroFilme = new javax.swing.JTextField();
        labelCensuraFilme = new javax.swing.JLabel();
        txtCensuraFilme = new javax.swing.JTextField();
        painelPeca = new javax.swing.JPanel();
        labelCadastrarPeca = new javax.swing.JLabel();
        labelNomePeca = new javax.swing.JLabel();
        labelCompanhiaPeca = new javax.swing.JLabel();
        labelGeneroPeca = new javax.swing.JLabel();
        labelCensuraPeca = new javax.swing.JLabel();
        txtNomePeca = new javax.swing.JTextField();
        txtCompanhiaPeca = new javax.swing.JTextField();
        txtGeneroPeca = new javax.swing.JTextField();
        txtCemsuraPeca = new javax.swing.JTextField();
        painelShow = new javax.swing.JPanel();
        labelCadastrarShow = new javax.swing.JLabel();
        labelNomeShow = new javax.swing.JLabel();
        labelArtistaShow = new javax.swing.JLabel();
        labelEstiloShow = new javax.swing.JLabel();
        txtNomeShow = new javax.swing.JTextField();
        txtArtistaShow = new javax.swing.JTextField();
        txtEstilhoShow = new javax.swing.JTextField();
        painelAmbiente = new javax.swing.JPanel();
        labelCadastrarAmbiente = new javax.swing.JLabel();
        labelNomeAmbiente = new javax.swing.JLabel();
        labelDescricaoAmbiente = new javax.swing.JLabel();
        labelPontoReferenciaAmbiente = new javax.swing.JLabel();
        labelSetorAmbiente = new javax.swing.JLabel();
        labelCapacidadeAmbiente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescricaoAmbiente = new javax.swing.JTextArea();
        txtNomeSetorAmbiente = new javax.swing.JTextField();
        txtCapacidadeSetorAmbiente = new javax.swing.JTextField();
        txtNomeAmbiente = new javax.swing.JTextField();
        txtPontoReferenciaAmbiente = new javax.swing.JTextField();
        painelIngresso = new javax.swing.JPanel();
        painelContato = new javax.swing.JPanel();
        painelGerarPdf = new javax.swing.JPanel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuPrincipal1 = new javax.swing.JMenu();
        subMenuAbrirPasta = new javax.swing.JMenuItem();
        subMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelPrincipal.setLayout(new java.awt.CardLayout());

        labelCadastrarEvento.setText("Cadasrtrar Evento");

        comboxCadastrarEvento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Esporte", "Filme", "Peça", "Show" }));

        btnCadastrarEventoOk.setText("OK");

        jLabel1.setText("Gerar PDF");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Esporte", "Filme", "Peça", "Show" }));

        btnGerarPdfOk.setText("OK");

        javax.swing.GroupLayout painelCadastrarLayout = new javax.swing.GroupLayout(painelCadastrar);
        painelCadastrar.setLayout(painelCadastrarLayout);
        painelCadastrarLayout.setHorizontalGroup(
            painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(painelCadastrarLayout.createSequentialGroup()
                        .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCadastrarEvento)
                            .addComponent(comboxCadastrarEvento, 0, 191, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarEventoOk)
                            .addComponent(btnGerarPdfOk))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        painelCadastrarLayout.setVerticalGroup(
            painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelCadastrarEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxCadastrarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarEventoOk))
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerarPdfOk))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        PainelPrincipal.add(painelCadastrar, "card2");

        labelTituloCadastrarEsporte.setText("Cadastrar Esporte");

        cadastrarEquipeEsporte.setColumns(20);
        cadastrarEquipeEsporte.setRows(5);
        cadastrarEquipeEsporte.setText("Digite o nome dos mebros da equipe sepadados por \";\"");
        cadastrarEquipeEsporteScroll.setViewportView(cadastrarEquipeEsporte);

        labelEquipeEsporte.setText("Equipe: ");

        labelNomeEsporte.setText("Nome: ");

        txtNomeEsporte.setText("Digite o nome da equipe: ");

        javax.swing.GroupLayout painelEsporteLayout = new javax.swing.GroupLayout(painelEsporte);
        painelEsporte.setLayout(painelEsporteLayout);
        painelEsporteLayout.setHorizontalGroup(
            painelEsporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEsporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarEquipeEsporteScroll)
                    .addGroup(painelEsporteLayout.createSequentialGroup()
                        .addGroup(painelEsporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTituloCadastrarEsporte)
                            .addComponent(labelEquipeEsporte)
                            .addGroup(painelEsporteLayout.createSequentialGroup()
                                .addComponent(labelNomeEsporte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeEsporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelEsporteLayout.setVerticalGroup(
            painelEsporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloCadastrarEsporte)
                .addGap(18, 18, 18)
                .addGroup(painelEsporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeEsporte)
                    .addComponent(txtNomeEsporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(labelEquipeEsporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarEquipeEsporteScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PainelPrincipal.add(painelEsporte, "card3");

        labelCadastrarFilme.setText("Cadastrar Filme");

        labelNomeFilme.setText("Nome: ");

        txtNomeFilme.setText("Nome do filme: ");

        labelGeneroFilme.setText("Genêro: ");

        txtGeneroFilme.setText("Genêro do filme:");

        labelCensuraFilme.setText("Censura: ");

        txtCensuraFilme.setText("Censura do filme: ");

        javax.swing.GroupLayout painelFilmeLayout = new javax.swing.GroupLayout(painelFilme);
        painelFilme.setLayout(painelFilmeLayout);
        painelFilmeLayout.setHorizontalGroup(
            painelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFilmeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastrarFilme)
                    .addGroup(painelFilmeLayout.createSequentialGroup()
                        .addComponent(labelGeneroFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGeneroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelFilmeLayout.createSequentialGroup()
                        .addComponent(labelNomeFilme)
                        .addGap(30, 30, 30)
                        .addComponent(txtNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelFilmeLayout.createSequentialGroup()
                        .addComponent(labelCensuraFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCensuraFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        painelFilmeLayout.setVerticalGroup(
            painelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFilmeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastrarFilme)
                .addGap(18, 18, 18)
                .addGroup(painelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeFilme)
                    .addComponent(txtNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGeneroFilme)
                    .addComponent(txtGeneroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCensuraFilme)
                    .addComponent(txtCensuraFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        PainelPrincipal.add(painelFilme, "card4");

        labelCadastrarPeca.setText("Cadastrar Peça");

        labelNomePeca.setText("Nome: ");

        labelCompanhiaPeca.setText("Companhia: ");

        labelGeneroPeca.setText("Genêro: ");

        labelCensuraPeca.setText("Censura: ");

        txtNomePeca.setText("Nome da peça: ");

        txtCompanhiaPeca.setText("Companhia da peça: ");

        txtGeneroPeca.setText("Genêro da peça: ");

        txtCemsuraPeca.setText("Censura da pela: ");

        javax.swing.GroupLayout painelPecaLayout = new javax.swing.GroupLayout(painelPeca);
        painelPeca.setLayout(painelPecaLayout);
        painelPecaLayout.setHorizontalGroup(
            painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastrarPeca)
                    .addGroup(painelPecaLayout.createSequentialGroup()
                        .addComponent(labelNomePeca)
                        .addGap(52, 52, 52)
                        .addComponent(txtNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPecaLayout.createSequentialGroup()
                        .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCompanhiaPeca)
                            .addComponent(labelGeneroPeca)
                            .addComponent(labelCensuraPeca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCemsuraPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeneroPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCompanhiaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        painelPecaLayout.setVerticalGroup(
            painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastrarPeca)
                .addGap(18, 18, 18)
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomePeca)
                    .addComponent(txtNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompanhiaPeca)
                    .addComponent(txtCompanhiaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGeneroPeca)
                    .addComponent(txtGeneroPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCensuraPeca)
                    .addComponent(txtCemsuraPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        PainelPrincipal.add(painelPeca, "card9");

        labelCadastrarShow.setText("Cadastrar Show");

        labelNomeShow.setText("Nome: ");

        labelArtistaShow.setText("Artista: ");

        labelEstiloShow.setText("Estilo: ");

        txtNomeShow.setText("Nome Show: ");

        txtArtistaShow.setText("Nome Artista: ");

        txtEstilhoShow.setText("Estilo Show: ");

        javax.swing.GroupLayout painelShowLayout = new javax.swing.GroupLayout(painelShow);
        painelShow.setLayout(painelShowLayout);
        painelShowLayout.setHorizontalGroup(
            painelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelShowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastrarShow)
                    .addGroup(painelShowLayout.createSequentialGroup()
                        .addGroup(painelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomeShow)
                            .addComponent(labelArtistaShow)
                            .addComponent(labelEstiloShow))
                        .addGap(20, 20, 20)
                        .addGroup(painelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstilhoShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArtistaShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        painelShowLayout.setVerticalGroup(
            painelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelShowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastrarShow)
                .addGap(18, 18, 18)
                .addGroup(painelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeShow)
                    .addComponent(txtNomeShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArtistaShow)
                    .addComponent(txtArtistaShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstiloShow)
                    .addComponent(txtEstilhoShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        PainelPrincipal.add(painelShow, "card5");

        labelCadastrarAmbiente.setText("Cadastrar Ambiente");

        labelNomeAmbiente.setText("Nome Ambiente: ");

        labelDescricaoAmbiente.setText("Descrição: ");

        labelPontoReferenciaAmbiente.setText("Ponto de Referência: ");

        labelSetorAmbiente.setText("Setor: ");

        labelCapacidadeAmbiente.setText("Capacidade: ");

        campoDescricaoAmbiente.setColumns(20);
        campoDescricaoAmbiente.setRows(5);
        jScrollPane1.setViewportView(campoDescricaoAmbiente);

        txtNomeSetorAmbiente.setText("Nome do Setor:");

        txtCapacidadeSetorAmbiente.setText("Capacidade: ");

        txtNomeAmbiente.setText("Nome do Ambiente: ");

        txtPontoReferenciaAmbiente.setText("Ponto de Referência: ");

        javax.swing.GroupLayout painelAmbienteLayout = new javax.swing.GroupLayout(painelAmbiente);
        painelAmbiente.setLayout(painelAmbienteLayout);
        painelAmbienteLayout.setHorizontalGroup(
            painelAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAmbienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCadastrarAmbiente)
                    .addComponent(labelDescricaoAmbiente)
                    .addGroup(painelAmbienteLayout.createSequentialGroup()
                        .addComponent(labelPontoReferenciaAmbiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPontoReferenciaAmbiente))
                    .addGroup(painelAmbienteLayout.createSequentialGroup()
                        .addComponent(labelSetorAmbiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeSetorAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCapacidadeAmbiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCapacidadeSetorAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAmbienteLayout.createSequentialGroup()
                        .addComponent(labelNomeAmbiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeAmbiente))
                    .addComponent(jScrollPane1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        painelAmbienteLayout.setVerticalGroup(
            painelAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAmbienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastrarAmbiente)
                .addGap(18, 18, 18)
                .addGroup(painelAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAmbiente)
                    .addComponent(txtNomeAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelDescricaoAmbiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(painelAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPontoReferenciaAmbiente)
                    .addComponent(txtPontoReferenciaAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(painelAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSetorAmbiente)
                    .addComponent(labelCapacidadeAmbiente)
                    .addComponent(txtNomeSetorAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacidadeSetorAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PainelPrincipal.add(painelAmbiente, "card6");

        javax.swing.GroupLayout painelIngressoLayout = new javax.swing.GroupLayout(painelIngresso);
        painelIngresso.setLayout(painelIngressoLayout);
        painelIngressoLayout.setHorizontalGroup(
            painelIngressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelIngressoLayout.setVerticalGroup(
            painelIngressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        PainelPrincipal.add(painelIngresso, "card7");

        javax.swing.GroupLayout painelContatoLayout = new javax.swing.GroupLayout(painelContato);
        painelContato.setLayout(painelContatoLayout);
        painelContatoLayout.setHorizontalGroup(
            painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelContatoLayout.setVerticalGroup(
            painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        PainelPrincipal.add(painelContato, "card10");

        javax.swing.GroupLayout painelGerarPdfLayout = new javax.swing.GroupLayout(painelGerarPdf);
        painelGerarPdf.setLayout(painelGerarPdfLayout);
        painelGerarPdfLayout.setHorizontalGroup(
            painelGerarPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelGerarPdfLayout.setVerticalGroup(
            painelGerarPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        PainelPrincipal.add(painelGerarPdf, "card8");

        menuPrincipal1.setText("Arquivo");

        subMenuAbrirPasta.setText("Abrir Pasta");
        subMenuAbrirPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuAbrirPastaActionPerformed(evt);
            }
        });
        menuPrincipal1.add(subMenuAbrirPasta);

        subMenuSair.setText("Sair");
        subMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSairActionPerformed(evt);
            }
        });
        menuPrincipal1.add(subMenuSair);

        menuPrincipal.add(menuPrincipal1);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuAbrirPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuAbrirPastaActionPerformed
        abrirPasta pasta = new abrirPasta();
        try {
            pasta.irURL();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro na pasta!");
        }
    }//GEN-LAST:event_subMenuAbrirPastaActionPerformed

    private void subMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSairActionPerformed

        int opcao = JOptionPane.showConfirmDialog(null, "Deseja Realmente Sair? ");
        if (opcao == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_subMenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarPangletoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarPangletoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarPangletoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarPangletoEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerarPangletoEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JButton btnCadastrarEventoOk;
    private javax.swing.JButton btnGerarPdfOk;
    private javax.swing.JTextArea cadastrarEquipeEsporte;
    private javax.swing.JScrollPane cadastrarEquipeEsporteScroll;
    private javax.swing.JTextArea campoDescricaoAmbiente;
    private javax.swing.JComboBox comboxCadastrarEvento;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelArtistaShow;
    private javax.swing.JLabel labelCadastrarAmbiente;
    private javax.swing.JLabel labelCadastrarEvento;
    private javax.swing.JLabel labelCadastrarFilme;
    private javax.swing.JLabel labelCadastrarPeca;
    private javax.swing.JLabel labelCadastrarShow;
    private javax.swing.JLabel labelCapacidadeAmbiente;
    private javax.swing.JLabel labelCensuraFilme;
    private javax.swing.JLabel labelCensuraPeca;
    private javax.swing.JLabel labelCompanhiaPeca;
    private javax.swing.JLabel labelDescricaoAmbiente;
    private javax.swing.JLabel labelEquipeEsporte;
    private javax.swing.JLabel labelEstiloShow;
    private javax.swing.JLabel labelGeneroFilme;
    private javax.swing.JLabel labelGeneroPeca;
    private javax.swing.JLabel labelNomeAmbiente;
    private javax.swing.JLabel labelNomeEsporte;
    private javax.swing.JLabel labelNomeFilme;
    private javax.swing.JLabel labelNomePeca;
    private javax.swing.JLabel labelNomeShow;
    private javax.swing.JLabel labelPontoReferenciaAmbiente;
    private javax.swing.JLabel labelSetorAmbiente;
    private javax.swing.JLabel labelTituloCadastrarEsporte;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuPrincipal1;
    private javax.swing.JPanel painelAmbiente;
    private javax.swing.JPanel painelCadastrar;
    private javax.swing.JPanel painelContato;
    private javax.swing.JPanel painelEsporte;
    private javax.swing.JPanel painelFilme;
    private javax.swing.JPanel painelGerarPdf;
    private javax.swing.JPanel painelIngresso;
    private javax.swing.JPanel painelPeca;
    private javax.swing.JPanel painelShow;
    private javax.swing.JMenuItem subMenuAbrirPasta;
    private javax.swing.JMenuItem subMenuSair;
    private javax.swing.JTextField txtArtistaShow;
    private javax.swing.JTextField txtCapacidadeSetorAmbiente;
    private javax.swing.JTextField txtCemsuraPeca;
    private javax.swing.JTextField txtCensuraFilme;
    private javax.swing.JTextField txtCompanhiaPeca;
    private javax.swing.JTextField txtEstilhoShow;
    private javax.swing.JTextField txtGeneroFilme;
    private javax.swing.JTextField txtGeneroPeca;
    private javax.swing.JTextField txtNomeAmbiente;
    private javax.swing.JTextField txtNomeEsporte;
    private javax.swing.JTextField txtNomeFilme;
    private javax.swing.JTextField txtNomePeca;
    private javax.swing.JTextField txtNomeSetorAmbiente;
    private javax.swing.JTextField txtNomeShow;
    private javax.swing.JTextField txtPontoReferenciaAmbiente;
    // End of variables declaration//GEN-END:variables
}
