/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

/**
 *
 * @author herlan
 */
public class PainelDetalheEvento extends javax.swing.JPanel {

    /**
     * Creates new form PainelDetalheEvento
     */
    public PainelDetalheEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDetalhesEvento = new javax.swing.JLabel();
        labelSinopseEvento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoSinopseEvento = new javax.swing.JTextArea();
        labelDescricaoEvento = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoDescricaoEvento = new javax.swing.JTextArea();
        btnVoltarAmbiente = new javax.swing.JButton();
        btnAvançarAmbiente = new javax.swing.JButton();
        labelDuracaoEvento = new javax.swing.JLabel();
        labelDataHoraEvento = new javax.swing.JLabel();
        txtDuracaoExento = new javax.swing.JTextField();
        formatedDataHoraEvento = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(674, 381));

        labelDetalhesEvento.setText("Detalhes do Evento");

        labelSinopseEvento.setText("Sinospse: ");

        campoSinopseEvento.setColumns(20);
        campoSinopseEvento.setRows(5);
        jScrollPane2.setViewportView(campoSinopseEvento);

        labelDescricaoEvento.setText("Descrição: ");

        campoDescricaoEvento.setColumns(20);
        campoDescricaoEvento.setRows(5);
        jScrollPane3.setViewportView(campoDescricaoEvento);

        btnVoltarAmbiente.setText("Voltar");

        btnAvançarAmbiente.setText("Avançar");

        labelDuracaoEvento.setText("Duração: ");

        labelDataHoraEvento.setText("Data e Hora do Evento:");

        txtDuracaoExento.setText("Duração");

        try {
            formatedDataHoraEvento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(labelDetalhesEvento)
                    .addComponent(labelDescricaoEvento)
                    .addComponent(labelSinopseEvento)
                    .addComponent(jScrollPane3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDuracaoEvento)
                            .addComponent(labelDataHoraEvento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtDuracaoExento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(formatedDataHoraEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarAmbiente)
                .addGap(18, 18, 18)
                .addComponent(btnAvançarAmbiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(labelDetalhesEvento)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSinopseEvento)
                    .addComponent(labelDuracaoEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescricaoEvento)
                            .addComponent(labelDataHoraEvento)))
                    .addComponent(txtDuracaoExento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatedDataHoraEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvançarAmbiente)
                    .addComponent(btnVoltarAmbiente))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvançarAmbiente;
    private javax.swing.JButton btnVoltarAmbiente;
    private javax.swing.JTextArea campoDescricaoEvento;
    private javax.swing.JTextArea campoSinopseEvento;
    private javax.swing.JFormattedTextField formatedDataHoraEvento;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDataHoraEvento;
    private javax.swing.JLabel labelDescricaoEvento;
    private javax.swing.JLabel labelDetalhesEvento;
    private javax.swing.JLabel labelDuracaoEvento;
    private javax.swing.JLabel labelSinopseEvento;
    private javax.swing.JTextField txtDuracaoExento;
    // End of variables declaration//GEN-END:variables
}
