/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

/**
 *
 * @author herlan
 */
public class PainelAmbiente extends javax.swing.JPanel {

    /**
     * Creates new form PainelAmbiente
     */
    public PainelAmbiente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCadastrarAmbiente = new javax.swing.JLabel();
        labelNomeAmbiente = new javax.swing.JLabel();
        txtNomeAmbiente = new javax.swing.JTextField();
        labelDescricaoAmbiente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescricaoAmbiente = new javax.swing.JTextArea();
        labelPontoReferenciaAmbiente = new javax.swing.JLabel();
        txtPontoReferenciaAmbiente = new javax.swing.JTextField();
        labelSetorAmbiente = new javax.swing.JLabel();
        txtNomeSetorAmbiente = new javax.swing.JTextField();
        labelCapacidadeAmbiente = new javax.swing.JLabel();
        txtCapacidadeSetorAmbiente = new javax.swing.JTextField();
        btnVoltarAmbiente = new javax.swing.JButton();
        btnAvançarAmbiente = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(674, 381));

        labelCadastrarAmbiente.setText("Cadastrar Ambiente");

        labelNomeAmbiente.setText("Nome Ambiente: ");

        txtNomeAmbiente.setText("Nome do Ambiente: ");

        labelDescricaoAmbiente.setText("Descrição: ");

        campoDescricaoAmbiente.setColumns(20);
        campoDescricaoAmbiente.setRows(5);
        jScrollPane1.setViewportView(campoDescricaoAmbiente);

        labelPontoReferenciaAmbiente.setText("Ponto de Referência: ");

        txtPontoReferenciaAmbiente.setText("Ponto de Referência: ");

        labelSetorAmbiente.setText("Setor: ");

        txtNomeSetorAmbiente.setText("Nome do Setor:");

        labelCapacidadeAmbiente.setText("Capacidade: ");

        txtCapacidadeSetorAmbiente.setText("Capacidade: ");

        btnVoltarAmbiente.setText("Voltar");

        btnAvançarAmbiente.setText("Avançar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarAmbiente)
                .addGap(18, 18, 18)
                .addComponent(btnAvançarAmbiente)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSetorAmbiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeSetorAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCapacidadeAmbiente)
                        .addGap(6, 6, 6)
                        .addComponent(txtCapacidadeSetorAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPontoReferenciaAmbiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPontoReferenciaAmbiente, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNomeAmbiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeAmbiente))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDescricaoAmbiente)
                                    .addComponent(labelCadastrarAmbiente))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastrarAmbiente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAmbiente)
                    .addComponent(txtNomeAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelDescricaoAmbiente)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPontoReferenciaAmbiente)
                    .addComponent(txtPontoReferenciaAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSetorAmbiente)
                    .addComponent(labelCapacidadeAmbiente)
                    .addComponent(txtNomeSetorAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacidadeSetorAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvançarAmbiente)
                    .addComponent(btnVoltarAmbiente))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvançarAmbiente;
    private javax.swing.JButton btnVoltarAmbiente;
    private javax.swing.JTextArea campoDescricaoAmbiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCadastrarAmbiente;
    private javax.swing.JLabel labelCapacidadeAmbiente;
    private javax.swing.JLabel labelDescricaoAmbiente;
    private javax.swing.JLabel labelNomeAmbiente;
    private javax.swing.JLabel labelPontoReferenciaAmbiente;
    private javax.swing.JLabel labelSetorAmbiente;
    private javax.swing.JTextField txtCapacidadeSetorAmbiente;
    private javax.swing.JTextField txtNomeAmbiente;
    private javax.swing.JTextField txtNomeSetorAmbiente;
    private javax.swing.JTextField txtPontoReferenciaAmbiente;
    // End of variables declaration//GEN-END:variables
}
