/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

/**
 *
 * @author herlan
 */
public class Painelngresso extends javax.swing.JPanel {

    /**
     * Creates new form PainelIngresso
     */
    public Painelngresso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelngressoEvento = new javax.swing.JLabel();
        labelValorIngresso = new javax.swing.JLabel();
        labelQuantidadeIngresso = new javax.swing.JLabel();
        labelPromocaoIngresso = new javax.swing.JLabel();
        labelMensagemIngressoPromocao = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        campoMensagemPromocaoIngresso = new javax.swing.JTextArea();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        labelQuantidadeDisponivelPromocaoIngresso = new javax.swing.JLabel();
        txtQuantudadeDisponivelPromocaoIngresso = new javax.swing.JTextField();
        txtlValorDescontoPromocaoIngresso = new javax.swing.JTextField();
        labelValorDescontoPromocaoIngresso = new javax.swing.JLabel();
        btnVoltarAmbiente = new javax.swing.JButton();
        btnAvançarAmbiente = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(674, 381));

        labelngressoEvento.setText("Ingresso");

        labelValorIngresso.setText("Valor: ");

        labelQuantidadeIngresso.setText("Quantidade: ");

        labelPromocaoIngresso.setText("Promoção");

        labelMensagemIngressoPromocao.setText("Mensagem: ");

        campoMensagemPromocaoIngresso.setColumns(20);
        campoMensagemPromocaoIngresso.setRows(5);
        jScrollPane5.setViewportView(campoMensagemPromocaoIngresso);

        jTextField4.setText("Quantidade: ");

        jTextField3.setText("Valor: ");

        labelQuantidadeDisponivelPromocaoIngresso.setText("Quantidade Disponivél: ");

        txtQuantudadeDisponivelPromocaoIngresso.setText("Quantidade Disponivél");

        txtlValorDescontoPromocaoIngresso.setText("Valor de Desconto");

        labelValorDescontoPromocaoIngresso.setText("Valor de Desconto: ");

        btnVoltarAmbiente.setText("Voltar");

        btnAvançarAmbiente.setText("Avançar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMensagemIngressoPromocao)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelValorDescontoPromocaoIngresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtlValorDescontoPromocaoIngresso)
                            .addComponent(txtQuantudadeDisponivelPromocaoIngresso)
                            .addComponent(labelQuantidadeDisponivelPromocaoIngresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelValorIngresso)
                                    .addComponent(labelQuantidadeIngresso))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelngressoEvento)
                            .addComponent(labelPromocaoIngresso))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarAmbiente)
                .addGap(18, 18, 18)
                .addComponent(btnAvançarAmbiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelngressoEvento)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelValorIngresso)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidadeIngresso)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelPromocaoIngresso)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMensagemIngressoPromocao)
                    .addComponent(labelQuantidadeDisponivelPromocaoIngresso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtQuantudadeDisponivelPromocaoIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelValorDescontoPromocaoIngresso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtlValorDescontoPromocaoIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvançarAmbiente)
                    .addComponent(btnVoltarAmbiente))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvançarAmbiente;
    private javax.swing.JButton btnVoltarAmbiente;
    private javax.swing.JTextArea campoMensagemPromocaoIngresso;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel labelMensagemIngressoPromocao;
    private javax.swing.JLabel labelPromocaoIngresso;
    private javax.swing.JLabel labelQuantidadeDisponivelPromocaoIngresso;
    private javax.swing.JLabel labelQuantidadeIngresso;
    private javax.swing.JLabel labelValorDescontoPromocaoIngresso;
    private javax.swing.JLabel labelValorIngresso;
    private javax.swing.JLabel labelngressoEvento;
    private javax.swing.JTextField txtQuantudadeDisponivelPromocaoIngresso;
    private javax.swing.JTextField txtlValorDescontoPromocaoIngresso;
    // End of variables declaration//GEN-END:variables
}
