/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

/**
 *
 * @author herlan
 */
public class PainelPeca extends javax.swing.JPanel {

    /**
     * Creates new form PainelPeca
     */
    public PainelPeca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCadastrarPeca = new javax.swing.JLabel();
        labelNomePeca = new javax.swing.JLabel();
        labelCompanhiaPeca = new javax.swing.JLabel();
        labelGeneroPeca = new javax.swing.JLabel();
        labelCensuraPeca = new javax.swing.JLabel();
        txtCemsuraPeca = new javax.swing.JTextField();
        txtGeneroPeca = new javax.swing.JTextField();
        txtCompanhiaPeca = new javax.swing.JTextField();
        txtNomePeca = new javax.swing.JTextField();
        btnVoltarAmbiente = new javax.swing.JButton();
        btnAvançarAmbiente = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(674, 381));

        labelCadastrarPeca.setText("Cadastrar Peça");

        labelNomePeca.setText("Nome: ");

        labelCompanhiaPeca.setText("Companhia: ");

        labelGeneroPeca.setText("Genêro: ");

        labelCensuraPeca.setText("Censura: ");

        txtCemsuraPeca.setText("Censura da pela: ");

        txtGeneroPeca.setText("Genêro da peça: ");

        txtCompanhiaPeca.setText("Companhia da peça: ");

        txtNomePeca.setText("Nome da peça: ");

        btnVoltarAmbiente.setText("Voltar");

        btnAvançarAmbiente.setText("Avançar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNomePeca)
                        .addGap(52, 52, 52)
                        .addComponent(txtNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCompanhiaPeca)
                            .addComponent(labelGeneroPeca)
                            .addComponent(labelCensuraPeca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompanhiaPeca)
                            .addComponent(txtGeneroPeca)
                            .addComponent(txtCemsuraPeca)))
                    .addComponent(labelCadastrarPeca))
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarAmbiente)
                .addGap(18, 18, 18)
                .addComponent(btnAvançarAmbiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastrarPeca)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomePeca)
                    .addComponent(txtNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompanhiaPeca)
                    .addComponent(txtCompanhiaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGeneroPeca)
                    .addComponent(txtGeneroPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCensuraPeca)
                    .addComponent(txtCemsuraPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvançarAmbiente)
                    .addComponent(btnVoltarAmbiente))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvançarAmbiente;
    private javax.swing.JButton btnVoltarAmbiente;
    private javax.swing.JLabel labelCadastrarPeca;
    private javax.swing.JLabel labelCensuraPeca;
    private javax.swing.JLabel labelCompanhiaPeca;
    private javax.swing.JLabel labelGeneroPeca;
    private javax.swing.JLabel labelNomePeca;
    private javax.swing.JTextField txtCemsuraPeca;
    private javax.swing.JTextField txtCompanhiaPeca;
    private javax.swing.JTextField txtGeneroPeca;
    private javax.swing.JTextField txtNomePeca;
    // End of variables declaration//GEN-END:variables
}
