/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

/**
 *
 * @author herlan
 */
public class PainelContato extends javax.swing.JPanel {

    /**
     * Creates new form PainelContato
     */
    public PainelContato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelContatoEvento = new javax.swing.JLabel();
        labelNomeContato = new javax.swing.JLabel();
        labelTelefoneContato = new javax.swing.JLabel();
        labelEmailContato = new javax.swing.JLabel();
        labelEnderecoContato = new javax.swing.JLabel();
        txtEmailContato = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        campoEnderecoContato = new javax.swing.JTextArea();
        txtTelefoneContato = new javax.swing.JTextField();
        txtNomeContato = new javax.swing.JTextField();
        btnVoltarAmbiente = new javax.swing.JButton();
        btnAvançarAmbiente = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(674, 381));

        labelContatoEvento.setText("Contato");

        labelNomeContato.setText("Nome: ");

        labelTelefoneContato.setText("Telefone: ");

        labelEmailContato.setText("Email: ");

        labelEnderecoContato.setText("Endereço: ");

        txtEmailContato.setText("Email: ");

        campoEnderecoContato.setColumns(20);
        campoEnderecoContato.setRows(5);
        jScrollPane4.setViewportView(campoEnderecoContato);

        txtTelefoneContato.setText("Telefone: ");

        txtNomeContato.setText("Nome: ");

        btnVoltarAmbiente.setText("Voltar");

        btnAvançarAmbiente.setText("Avançar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltarAmbiente)
                        .addGap(18, 18, 18)
                        .addComponent(btnAvançarAmbiente))
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEnderecoContato)
                            .addComponent(labelContatoEvento))
                        .addGap(0, 301, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTelefoneContato)
                            .addComponent(labelEmailContato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailContato)
                            .addComponent(txtTelefoneContato)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNomeContato)
                        .addGap(40, 40, 40)
                        .addComponent(txtNomeContato)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelContatoEvento)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeContato)
                    .addComponent(txtNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefoneContato)
                    .addComponent(txtTelefoneContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmailContato)
                    .addComponent(txtEmailContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelEnderecoContato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvançarAmbiente)
                    .addComponent(btnVoltarAmbiente))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvançarAmbiente;
    private javax.swing.JButton btnVoltarAmbiente;
    private javax.swing.JTextArea campoEnderecoContato;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelContatoEvento;
    private javax.swing.JLabel labelEmailContato;
    private javax.swing.JLabel labelEnderecoContato;
    private javax.swing.JLabel labelNomeContato;
    private javax.swing.JLabel labelTelefoneContato;
    private javax.swing.JTextField txtEmailContato;
    private javax.swing.JTextField txtNomeContato;
    private javax.swing.JTextField txtTelefoneContato;
    // End of variables declaration//GEN-END:variables
}
