/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

/**
 *
 * @author herlan
 */
public class PainelEsporte extends javax.swing.JPanel {

    /**
     * Creates new form PainelEsporte
     */
    public PainelCadastrar painelEsporte;

    public void setPainelCadastrar(PainelCadastrar painel) {
        this.painelEsporte = painel;
    }

    public PainelEsporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomeEsporte = new javax.swing.JLabel();
        btnAvançarAmbiente = new javax.swing.JButton();
        txtNomeEsporte = new javax.swing.JTextField();
        labelEquipeEsporte = new javax.swing.JLabel();
        btnVoltarAmbiente = new javax.swing.JButton();
        labelTituloCadastrarEsporte = new javax.swing.JLabel();
        cadastrarEquipeEsporteScroll1 = new javax.swing.JScrollPane();
        cadastrarEquipeEsporte1 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(674, 381));

        labelNomeEsporte.setText("Nome: ");

        btnAvançarAmbiente.setText("Avançar");

        txtNomeEsporte.setText("Digite o nome da equipe: ");

        labelEquipeEsporte.setText("Equipe: ");

        btnVoltarAmbiente.setText("Voltar");
        btnVoltarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAmbienteActionPerformed(evt);
            }
        });

        labelTituloCadastrarEsporte.setText("Cadastrar Esporte");

        cadastrarEquipeEsporte1.setColumns(20);
        cadastrarEquipeEsporte1.setRows(5);
        cadastrarEquipeEsporte1.setText("Digite o nome dos mebros da equipe sepadados por \";\"");
        cadastrarEquipeEsporteScroll1.setViewportView(cadastrarEquipeEsporte1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltarAmbiente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTituloCadastrarEsporte)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNomeEsporte)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNomeEsporte))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEquipeEsporte)
                                    .addComponent(cadastrarEquipeEsporteScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 107, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvançarAmbiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloCadastrarEsporte)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeEsporte)
                    .addComponent(txtNomeEsporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(labelEquipeEsporte)
                .addGap(18, 18, 18)
                .addComponent(cadastrarEquipeEsporteScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarAmbiente)
                    .addComponent(btnAvançarAmbiente))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAmbienteActionPerformed
        /*getPainelEsporte().setPainel(this);
         painelCadastrar.add(this.painelEsporte);
         CardLayout card = (CardLayout) painelCadastrar.getLayout();
         card.addLayoutComponent(this.painelEsporte, "PainelEsporte");
         card.show(painelCadastrar, "PainelEsporte");
         this.painelEsporte.setVisible(true);*/
        
        
    }//GEN-LAST:event_btnVoltarAmbienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvançarAmbiente;
    private javax.swing.JButton btnVoltarAmbiente;
    private javax.swing.JTextArea cadastrarEquipeEsporte1;
    private javax.swing.JScrollPane cadastrarEquipeEsporteScroll1;
    private javax.swing.JLabel labelEquipeEsporte;
    private javax.swing.JLabel labelNomeEsporte;
    private javax.swing.JLabel labelTituloCadastrarEsporte;
    private javax.swing.JTextField txtNomeEsporte;
    // End of variables declaration//GEN-END:variables
}
