/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author herlan
 */
public class PainelCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form PainelCadastrar
     */
    public PainelCadastrar() {
        initComponents();
    }
      
    public JPanel getPainelPrincipal() {
        return PainelPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        PainelCadastrar = new javax.swing.JPanel();
        labelCadastrarEvento1 = new javax.swing.JLabel();
        comboxCadastrarEvento1 = new javax.swing.JComboBox();
        labelGerarPdfCadastrar1 = new javax.swing.JLabel();
        comboxGerarPdfEvento1 = new javax.swing.JComboBox();
        btnGerarPdfOk1 = new javax.swing.JButton();
        btnCadastrarEventoOk1 = new javax.swing.JButton();
        menuPainelCadastrar = new javax.swing.JMenuBar();
        subMenuPainelCadastrar = new javax.swing.JMenu();
        itamAbrirPastaSubMenuPainelCadastrar = new javax.swing.JMenuItem();
        itamSairSubMenuPainelCadastrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PainelPrincipal.setLayout(new java.awt.CardLayout());

        labelCadastrarEvento1.setText("Cadasrtrar Evento");

        comboxCadastrarEvento1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Esporte", "Filme", "Peça", "Show" }));
        comboxCadastrarEvento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxCadastrarEvento1ActionPerformed(evt);
            }
        });

        labelGerarPdfCadastrar1.setText("Gerar PDF");

        comboxGerarPdfEvento1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Esporte", "Filme", "Peça", "Show" }));

        btnGerarPdfOk1.setText("OK");
        btnGerarPdfOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarPdfOk1ActionPerformed(evt);
            }
        });

        btnCadastrarEventoOk1.setText("OK");
        btnCadastrarEventoOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEventoOk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCadastrarLayout = new javax.swing.GroupLayout(PainelCadastrar);
        PainelCadastrar.setLayout(PainelCadastrarLayout);
        PainelCadastrarLayout.setHorizontalGroup(
            PainelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
            .addGroup(PainelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCadastrarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PainelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelGerarPdfCadastrar1)
                        .addGroup(PainelCadastrarLayout.createSequentialGroup()
                            .addGroup(PainelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelCadastrarEvento1)
                                .addComponent(comboxCadastrarEvento1, 0, 191, Short.MAX_VALUE)
                                .addComponent(comboxGerarPdfEvento1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(29, 29, 29)
                            .addGroup(PainelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCadastrarEventoOk1)
                                .addComponent(btnGerarPdfOk1))))
                    .addContainerGap(392, Short.MAX_VALUE)))
        );
        PainelCadastrarLayout.setVerticalGroup(
            PainelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(PainelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCadastrarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelCadastrarEvento1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PainelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboxCadastrarEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCadastrarEventoOk1))
                    .addGap(65, 65, 65)
                    .addComponent(labelGerarPdfCadastrar1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PainelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboxGerarPdfEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGerarPdfOk1))
                    .addContainerGap(179, Short.MAX_VALUE)))
        );

        PainelPrincipal.add(PainelCadastrar, "card2");

        subMenuPainelCadastrar.setText("Arquivo");

        itamAbrirPastaSubMenuPainelCadastrar.setText("Abrir Pasta");
        subMenuPainelCadastrar.add(itamAbrirPastaSubMenuPainelCadastrar);

        itamSairSubMenuPainelCadastrar.setText("Sair");
        subMenuPainelCadastrar.add(itamSairSubMenuPainelCadastrar);

        menuPainelCadastrar.add(subMenuPainelCadastrar);

        setJMenuBar(menuPainelCadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboxCadastrarEvento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCadastrarEvento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCadastrarEvento1ActionPerformed

    private void btnGerarPdfOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarPdfOk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarPdfOk1ActionPerformed

    private void btnCadastrarEventoOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEventoOk1ActionPerformed
        
    }//GEN-LAST:event_btnCadastrarEventoOk1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCadastrar;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JButton btnCadastrarEventoOk1;
    private javax.swing.JButton btnGerarPdfOk1;
    private javax.swing.JComboBox comboxCadastrarEvento1;
    private javax.swing.JComboBox comboxGerarPdfEvento1;
    private javax.swing.JMenuItem itamAbrirPastaSubMenuPainelCadastrar;
    private javax.swing.JMenuItem itamSairSubMenuPainelCadastrar;
    private javax.swing.JLabel labelCadastrarEvento1;
    private javax.swing.JLabel labelGerarPdfCadastrar1;
    private javax.swing.JMenuBar menuPainelCadastrar;
    private javax.swing.JMenu subMenuPainelCadastrar;
    // End of variables declaration//GEN-END:variables
}
