/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

/**
 *
 * @author herlan
 */
public class PainelGerarPdf extends javax.swing.JPanel {

    /**
     * Creates new form PainelGerarPdf
     */
    public PainelGerarPdf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboxListaEventoPDF = new javax.swing.JComboBox();
        btnSelecionarDataHoraPainelGerarPdf = new javax.swing.JButton();
        btnMenuPrincipalGerarPdf = new javax.swing.JButton();
        comboxSelecionarTamanhoPaginaPainelGerarPdf = new javax.swing.JComboBox();
        btnSelecionarTamanhoPaginaPainelGerarPdf = new javax.swing.JButton();
        comboxSelecionarCorPainelGerarPdf = new javax.swing.JComboBox();
        btnSelecionarCorPainelGerarPdf = new javax.swing.JButton();
        btnGerarPdfPainelGerarPdf = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(674, 381));

        comboxListaEventoPDF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione/Data Inclusão" }));
        comboxListaEventoPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxListaEventoPDFActionPerformed(evt);
            }
        });

        btnSelecionarDataHoraPainelGerarPdf.setText("OK");

        btnMenuPrincipalGerarPdf.setText("Menu Principal");

        comboxSelecionarTamanhoPaginaPainelGerarPdf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tamanho da Página: A1", "Tamanho da Página: A2", "Tamanho da Página: A3", "Tamanho da Página: A4", " " }));

        btnSelecionarTamanhoPaginaPainelGerarPdf.setText("OK");

        comboxSelecionarCorPainelGerarPdf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cor: Banco", "Cor: Preto", "Cor: Azul", "Cor: Cinza" }));

        btnSelecionarCorPainelGerarPdf.setText("OK");

        btnGerarPdfPainelGerarPdf.setText("Gerar PDF!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMenuPrincipalGerarPdf))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboxSelecionarCorPainelGerarPdf, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboxSelecionarTamanhoPaginaPainelGerarPdf, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboxListaEventoPDF, javax.swing.GroupLayout.Alignment.LEADING, 0, 240, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelecionarDataHoraPainelGerarPdf)
                            .addComponent(btnSelecionarTamanhoPaginaPainelGerarPdf)
                            .addComponent(btnSelecionarCorPainelGerarPdf))
                        .addGap(40, 40, 40)
                        .addComponent(btnGerarPdfPainelGerarPdf)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboxSelecionarTamanhoPaginaPainelGerarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelecionarTamanhoPaginaPainelGerarPdf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboxSelecionarCorPainelGerarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelecionarCorPainelGerarPdf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboxListaEventoPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelecionarDataHoraPainelGerarPdf)))
                    .addComponent(btnGerarPdfPainelGerarPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(btnMenuPrincipalGerarPdf)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboxListaEventoPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxListaEventoPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxListaEventoPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarPdfPainelGerarPdf;
    private javax.swing.JButton btnMenuPrincipalGerarPdf;
    private javax.swing.JButton btnSelecionarCorPainelGerarPdf;
    private javax.swing.JButton btnSelecionarDataHoraPainelGerarPdf;
    private javax.swing.JButton btnSelecionarTamanhoPaginaPainelGerarPdf;
    private javax.swing.JComboBox comboxListaEventoPDF;
    private javax.swing.JComboBox comboxSelecionarCorPainelGerarPdf;
    private javax.swing.JComboBox comboxSelecionarTamanhoPaginaPainelGerarPdf;
    // End of variables declaration//GEN-END:variables
}
