/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.panfleto.gui;

/**
 *
 * @author herlan
 */
public class PainelFilme extends javax.swing.JPanel {

    /**
     * Creates new form PainelFilme
     */
    public PainelFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCadastrarFilme = new javax.swing.JLabel();
        labelNomeFilme = new javax.swing.JLabel();
        labelGeneroFilme = new javax.swing.JLabel();
        labelCensuraFilme = new javax.swing.JLabel();
        txtCensuraFilme = new javax.swing.JTextField();
        txtGeneroFilme = new javax.swing.JTextField();
        txtNomeFilme = new javax.swing.JTextField();
        btnVoltarFilme = new javax.swing.JButton();
        btnAvançarFilme = new javax.swing.JButton();

        labelCadastrarFilme.setText("Cadastrar Filme");

        labelNomeFilme.setText("Nome: ");

        labelGeneroFilme.setText("Genêro: ");

        labelCensuraFilme.setText("Censura: ");

        txtCensuraFilme.setText("Censura do filme: ");

        txtGeneroFilme.setText("Genêro do filme:");

        txtNomeFilme.setText("Nome do filme: ");

        btnVoltarFilme.setText("Voltar");

        btnAvançarFilme.setText("Avançar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelGeneroFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGeneroFilme))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNomeFilme)
                        .addGap(30, 30, 30)
                        .addComponent(txtNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCensuraFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCensuraFilme))
                    .addComponent(labelCadastrarFilme))
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarFilme)
                .addGap(18, 18, 18)
                .addComponent(btnAvançarFilme)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastrarFilme)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeFilme)
                    .addComponent(txtNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGeneroFilme)
                    .addComponent(txtGeneroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCensuraFilme)
                    .addComponent(txtCensuraFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvançarFilme)
                    .addComponent(btnVoltarFilme))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvançarFilme;
    private javax.swing.JButton btnVoltarFilme;
    private javax.swing.JLabel labelCadastrarFilme;
    private javax.swing.JLabel labelCensuraFilme;
    private javax.swing.JLabel labelGeneroFilme;
    private javax.swing.JLabel labelNomeFilme;
    private javax.swing.JTextField txtCensuraFilme;
    private javax.swing.JTextField txtGeneroFilme;
    private javax.swing.JTextField txtNomeFilme;
    // End of variables declaration//GEN-END:variables
}
